export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SEARCH_POST = "SEARCH_POST";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const POSTS_LOADING = "POSTS_LOADING";
export const POSTS_LOAD_SUCCESS = "POSTS_LOAD_SUCCESS";
export const POSTS_LOAD_ERROR = "POSTS_LOAD_ERROR";

export const CREATE_POSTS_LOADING = "CREATE_POSTS_LOADING";
export const CREATE_POSTS_LOAD_SUCCESS = "CREATE_POSTS_LOAD_SUCCESS";
export const CREATE_POSTS_LOAD_ERROR = "CREATE_POSTS_LOAD_ERROR";

export const GET_EXPERIENCE_LOAD = "GET_EXPERIENCE_LOAD";
export const GET_EXPERIENCE_SUCCESS = "GET_EXPERIENCE_SUCCESS";
export const GET_EXPERIENCE_ERROR = "GET_EXPERIENCE_ERROR";

export const GET_EDUCATION_LOAD = "GET_EDUCATION_LOAD";
export const GET_EDUCATION_SUCCESS = "GET_EDUCATION_SUCCESS";
export const GET_EDUCATION_ERROR = "GET_EDUCATION_ERROR";

export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_ERROR = "DELETE_ERROR";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_LOAD_SUCCESS = "PROFILE_LOAD_SUCCESS";
export const PROFILE_LOAD_ERROR = "PROFILE_LOAD_ERROR";

export const USER_PROFILE_LOADING = "USER_PROFILE_LOADING";
export const USER_PROFILE_LOAD_SUCCESS = "USER_PROFILE_LOAD_SUCCESS";
export const USER_PROFILE_LOAD_ERROR = "USER_PROFILE_LOAD_ERROR";

export const ADD_CONTACT_LOAD = "ADD_CONTACT_LOAD";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_ERROR = "ADD_CONTACT_ERROR";

export const CLEAR_ADD_CONTACT = "CLEAR_ADD_CONTACT";
